log:
    level: info      # [trace,debug,info,warn,error,fatal,panic]
    timestamp: true  # boolean [true, false]

blockchain:
    # Polygon node RPC endpoint
    endpoint: https://matic-testnet-archive-rpc.bwarelabs.com
     # Polygon chain id, 80001 for testnet, 137 for production
    chain_id: 80001
    # Block confirmations, blocks are final after 128 confirmations
    confirmations: 128

packet_exchange:
    # supported backend where gateways connect to
    backend:
        type: semtech_udp       # backend [semtech_udp]
        udp_bind: 0.0.0.0:1680
        skip_crc_check: false
        fake_rx_time: false
    
    accounting: # forwarder doesn't yet support accounting
    
gateways:
    gateway_registry: 0xDAA93030749C7fE99B0A26Ac8074D49143A47C4e
    yaml_store: /var/home/bas/dev/thingsix/packet-handling/cmd/forwarder/gateways.store

routers:
    # default routers, usefull for personal routers that are not registered
    # but will receive all data
    default:
        # list with (default) router endpoints
        - endpoint: localhost:3200
          name: v47-indoor
          
    # retrieve routes snapshot every update_interval
    update_interval: 15m
   
    # indicate that routes must be fetched from the ThingsIX router API
    thingsix_api:
        # location where to fetch routes snapshot from
        endpoint: http://168.119.163.23/routers/v1/snapshot

# enable prometheus metrics endpoint
metrics:
    prometheus:
        host: 0.0.0.0
        port: 8888
        path: /metrics