# Copyright 2022 Stichting ThingsIX Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

log:
    level: info      # [trace,debug,info,warn,error,fatal,panic]
    timestamp: true

router:
  keyfile: /etc/thingsix-router/router.key

  forwarder:
    endpoint:
      host: 0.0.0.0
      port: 3200

  joinfiltergenerator:
    renew_interval: 5m
    chirpstack:
      # Enter global API key from Chirpstack
      api_key: api_key
      # set to true for local connections
      insecure: false
      # target uses GRPC target naming "dns:<hostname>:<port>"
      target: dns:chirpstack:8080

  integration:
    marshaler: protobuf
    mqtt:
      state_retained: true
      keep_alive: 30s
      max_reconnect_interval: 1m
      max_token_wait: 1s
      event_topic_template: eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      state_topic_template: eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      command_topic_template: eu868/gateway/{{ .GatewayID }}/command/#
      
      auth:
        generic:
          servers:
            - tcp://localhost:1883
          username: ""
          password: ""
          clean_session: true

metrics:
    prometheus:
        address: 0.0.0.0:9090
        path: /metrics
    
