log:
    level: info      # [trace,debug,info,warn,error,fatal,panic]
    timestamp: true

router:
  forwarder:
    host: 127.0.0.1
    port: 3200

  integration:
    marshaler: protobuf
    mqtt:
      state_retained: true
      keep_alive: 30s
      max_reconnect_interval: 1m
      max_token_wait: 1s
      event_topic_template: eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      state_topic_template: eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      command_topic_template: eu868/gateway/{{ .GatewayID }}/command/#
      
      auth:
        generic:
          servers:
            - tcp://localhost:1883
          username: ""
          password: ""
          clean_session: true
