name: Forwarder - Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args:
            GITHUB_ACCESS_TOKEN=${{secrets.GITHUB_ACCESS_TOKEN}}
          file: ./forwarder.Dockerfile
          platforms: linux/amd64, linux/arm64, linux/riscv64, linux/arm/v7, linux/arm/v6
          push: ${{github.event_name == 'release'}}